services:
  app:
    build: compose/phpfpm
    volumes: &appvolumes #create new volume associated to services (has to match with name, app ins this example)
      - ./src:/var/www/html
      - ./compose/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - sockdata:/sock
    extra_hosts:
      - "host.docker.internal:host-gateway" #muy importante para poder debugar scripts php (sandbox.php, etc)

  nginx:
    image: nginx:1.18-alpine
    ports:
      - "80:8000"
    volumes: *appvolumes #links to &appvolumes

  db:
    image: mariadb:10.4
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: compose/env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.5.0
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: compose/env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  rabbitmq:
    build: compose/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: compose/env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"

volumes:
  appdata:
  sockdata:
  dbdata:
  rabbitmqdata: